### ISSUE TITLE
Error on installation protocol_version

### ISSUE THREAD

**Issue by gepparta** [chgeo/show-shortcuts#1]
Hi, 
I am using Eclipse Oxygen.2 Release (4.7.2) and Java 1.8.
Using the update site: https://chgeo.github.io/show-shortcuts/

I am getting this error:
![image](https://user-images.githubusercontent.com/3863263/37704087-1c7bdbbe-2cf8-11e8-867d-b575657da49d.png)

With this similar plugin no error is thrown:
https://github.com/andau/abapCI
Update site:
https://raw.githubusercontent.com/andau/abapCI/master/com.abapci.updateSite/site.xml

**Comment by Orion1979** [comment]
Hi,

This [bug report](https://bugs.eclipse.org/bugs/show_bug.cgi?id=527434) suggests that Java 1.7 could be an issue.  Can you verify your Eclipse instance runs with Java 1.8?
Otherwise can you add the corresponding error log entry?

**Comment by gepparta** [comment]
I am running Eclipse with Java 1.8:
![image](https://user-images.githubusercontent.com/3863263/37766801-50c129d0-2dc8-11e8-84b6-4f9fe580e88e.png)

 

A working  solution would be to change from https to http:
![image](https://user-images.githubusercontent.com/3863263/37766538-75f9ec2e-2dc7-11e8-9dae-9618b9bac957.png)

**Comment by Orion1979** [comment]
For sure, with http as protocol the error doesn’t happen.  However, much like the rest of the Internet I would like to advertise https.

So, for the error, what seems fishy to me is the early access version of Java 1.8 that you are running (see the „-ea“ in the version string).  It could be that this one still has TLS 1.2 disabled (like Java 1.7 has).  Would you mind testing with a recent version?

**Comment by gepparta** [comment]
https://chgeo.github.io/show-shortcuts/
works well with Java 1.8.0_161. Thanks
