### ISSUE TITLE
Contribute to Eclipse

### ISSUE THREAD

**Issue by vogella** [chgeo/show-shortcuts#2]
Hi Christian,
this is a very useful feature. Would you like to contribute it to the Eclipse project?
Cheers, Lars

**Comment by chgeo** [comment]
Hey Lars,

sure I can do that.
I guess we should discuss the rest of the plan in an Eclipse bugzilla?  Would you like to create one that includes a little motivation from your side?

Christian

**Comment by vogella** [comment]
Hi Christian,

sounds great. I will open a new bug for that. cc @jonashungershausen

Best regards, Lars

**Comment by vogella** [comment]
Thanks @chgeo

https://bugs.eclipse.org/bugs/show_bug.cgi?id=540440

Before the migration I think we should polish the feature a bit. Is that Ok for you?

**Comment by chgeo** [comment]
Sure.  Let's continue the discussion over on [Eclipse bugzilla](https://bugs.eclipse.org/bugs/show_bug.cgi?id=540440).
